name: three_forge
description: "A high-performance, modular 3D game engine for Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  file_picker: ^10.1.2
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.4
  archive: ^4.0.9
  three_js: ^0.3.0
  three_js_terrain: ^0.3.0
  three_js_helpers: ^0.3.0
  three_js_transform_controls: ^0.3.0
  three_js_objects: ^0.3.0
  three_js_exporters: ^0.3.0
  three_js_modifers: ^0.3.0
  three_js_advanced_exporters: ^0.1.0
  three_js_tjs_loader: ^0.3.0
  three_js_video_texture: ^0.1.0
  dart_eval: ^0.8.3
  tflite_flutter: ^0.12.1
  css:
    git:
      url: https://github.com/Knightro63/css.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  permission_handler_apple:
    git:
      url: https://github.com/alex-melnyk/flutter-permission-handler.git 
      path: permission_handler_apple
  file_picker: ^10.1.9
  flutter_angle: ^0.4.1
  three_js_advanced_exporters: 
    path: ../three_js/packages/three_js_advanced_exporters
  three_js_advanced_loaders: 
    path: ../three_js/packages/three_js_advanced_loaders
  three_js_math: 
    path: ../three_js/packages/three_js_math
  three_js_geometry: 
    path: ../three_js/packages/three_js_geometry
  three_js_sensors: 
    path: ../three_js/packages/three_js_sensors
  three_js_controls: 
    path: ../three_js/packages/three_js_controls
  three_js_animations: 
    path: ../three_js/packages/three_js_animations
  three_js_modifers: 
    path: ../three_js/packages/three_js_modifers
  three_js_helpers: 
    path: ../three_js/packages/three_js_helpers
  three_js_angle_renderer: 
    path: ../three_js/packages/three_js_angle_renderer

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/terrain/
    - assets/src/