class Languages{
  String language;

  Languages(this.language);
	
  String operator [] (key) => values[language]![key] ?? '???';

	final values = {
		'fa': {
			'prompt/open': 'تمام داده های ذخیره نشده پاک خواهند شد آیا مطمئنید؟',
			'prompt/file/failedToOpenProject': 'خطایی در باز کردن پروژه پیش آمده',
			'prompt/export/noMeshSelected': 'هیچ Mesh ای انتخاب نکردید',
			'prompt/export/noObjectSelected': 'هیچ آبجکتی انتخاب نکردید!',
			'prompt/remove': 'آیا اطمینان دارید؟',
			'prompt/clear': 'هیستوری قبل و بعد (undo / redo) پاک خواهند شد آیا مطمئنید؟',
			'prompt/preserve': 'The history will be preserved across sessions.\nThis can have an impact on performance when working with textures.',
			'prompt/forbid': 'Undo/Redo disabled while scene is playing.',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC Shading: Only MeshStandardMaterial and MeshPhysicalMaterial are supported',

			'AddObject': 'افزودن آبجکت',
			'AddScript': 'افزودن اسکریپت',
			'MoveObject': 'جابجایی آبجکت',
			'MultiCmds': 'تغییرات گروهی',
			'RemoveObject': 'حذف آبجکت',
			'RemoveScript': 'حذف اسکریپت',
			'SetColor': 'تنظیم رنگ',
			'SetGeometry': 'تنظیم ژئومتری',
			'SetGeometryValue': 'تنظیم مقدار ژئومتری',
			'SetMaterialColor': 'تنظیم رنگ متریال',
			'SetMaterial': 'تنظیم متریال',
			'SetMaterialMap': 'تنظیم مپ متریال',
			'SetMaterialRange': 'تنظیم رنج متریال',
			'SetMaterialValue': 'تنظیم مقدار متریال',
			'SetMaterialVector': 'تنظیم وکتور متریال',
			'SetPosition': 'تنظیم پوزیشن',
			'SetRotation': 'تنظیم چرخش',
			'SetScale': 'تنظیم اندازه',
			'SetScene': 'تنظیم صحنه',
			'SetScriptValue': 'تنظیم مقدار اسکریپت',
			'SetShadowValue': 'تنظیم مقدار سایه',
			'SetUuid': 'تنظیم UUID',
			'SetValue': 'تنظیم مقدار',

			'file': 'فایل',
			'new': 'جدید',
			'empty': 'پروژه خالی',
			'arkanoid': 'آرکانوید',
			'camera': 'دوربین',
			'particles': 'Particles',
			'new/Pong': 'پونگ',
			'shaders': 'Shaders',
			'open': 'باز کردن',
			'save': 'ذخیره تغییرات',
			'import': 'ایمپورت',
			'export': 'اکسپورت',

			'edit': 'تغییر',
			'undo': 'بازگشت',
			'redo': 'بازگشت به جلو',
			'center': 'وسط',
			'clone': 'شبیه سازی',
			'delete': 'حذف',

			'add': 'افزودن',
			'group': 'گروه',

			'mesh': 'مش',
			'plane': 'صفحه',
			'box': 'باکس',
			'capsule': 'کپسول',
			'circle': 'دایره',
			'cylinder': 'سیلندر',
			'ring': 'حلقه',
			'sphere': 'کره',
			'dodecahedron': 'دوازده وجهی',
			'icosahedron': 'بیست وجهی',
			'octahedron': 'هشت وجهی',
			'tetrahedron': 'چهار وجهی',
			'torus': 'توروس (دونات)',
			'tube': 'لوله',
			'torusknot': 'torusknot',
			'lathe': 'Lathe',
			'sprite': 'Sprite',

			'light': 'نور',
			'ambient': 'محیط',
			'directional': 'جهت دار',
			'hemisphere': 'نیمکره',
			'point': 'مستقیم',
			'spot': 'نقطه ای',

			'perspective': 'پرسپکتیو',
			'orthographic': 'اورتوگرافیک',

			'autosave': 'ذخیره اتوماتیک',

			'view': 'نمایش',
			'fullscreen': 'تمام صفحه',
			'gridHelper': 'کمک کننده گرید',
			'cameraHelpers': 'کمک کننده دوربین',
			'lightHelpers': 'کمک کننده نور',
			'skeletonHelpers': 'کمک کننده اسکلتون',

			'help': 'کمک',
			'source_code': 'سورس کد',
			'icons': 'پک آیکون',
			'about': 'درباره ما',
			'manual': 'کتابچه راهنما',

			'animations': 'انیمیشن ها',
			'play': 'نمایش',
			'stop': 'توقف',
			'timescale': 'مقیاس زمانی',

			'scene': 'صحنه',
			'background': 'پس زمینه',
			'environment': 'محیط',
			'fog': 'مه',

			'object': 'آبجکت',
			'geometry': 'ژئومتری',
			'material': 'متریال',
			'script': 'اسکریپت',

			'type': 'انواع',
			'uuid': 'UUID',
			'name': 'نام',
			'position': 'پوزیشن',
			'rotation': 'چرخش',
			'scale': 'مقیاس',
			'fov': 'زاویه دید',
			'left': 'چپ',
			'right': 'راست',
			'top': 'بالا',
			'bottom': 'پایین',
			'near': 'نزدیک',
			'far': 'دور',
			'intensity': 'شدت',
			'color': 'رنگ',
			'groundcolor': 'رنگ زمینه',
			'distance': 'مسافت',
			'angle': 'زاویه',
			'penumbra': 'نیم سایه',
			'decay': 'پوسیدگی',
			'shadow': 'سایه',
			'shadowIntensity': 'شدت سایه',
			'shadowBias': 'انحراف سایه',
			'shadowNormalBias': 'انحراف معمول سایه',
			'shadowRadius': 'شعاع سایه',
			'cast': 'سایه انداختن',
			'receive': 'دریافت',
			'visible': 'آشکار',
			'frustumcull': 'فروستوم کال',
			'renderorder': 'ترتیب رندر',
			'userdata': 'داده کاربر',
			'exportjson': 'اکسپورت جیسون',

			'geometry/type': 'انواع',
			'geometry/new': 'جدید',
			'geometry/uuid': 'UUID',
			'geometry/name': 'نام',
			'geometry/bounds': 'محدوده',
			'geometry/userdata': 'داده کاربر',
			'geometry/show_vertex_normals': 'نمایش راس های معمول',
			'geometry/compute_vertex_normals': 'محاسبه راس های معمول',
			'geometry/compute_vertex_tangents': 'محاسبه مماس ها',
			'geometry/center': 'وسط',
			'geometry/export': 'اکسپورت جیسون',

			'width': 'عرض',
			'height': 'ارتفاع',
			'depth': 'عمق',
			'widthseg': 'ارجاع عرض',
			'heightseg': 'ارجاع ارتفاع',
			'depthseg': 'ارجاع عمق',

			'attributes': 'صفات',
			'index': 'شاخص',
			'morphAttributes': 'صفات شکل (مورف)',
			'morphRelative': 'صفات نسبی (رلتیو)',

			'radius': 'شعاع',
			'capseg': 'Cap Seg',
			'radialseg': 'Radial Seg',

			'segments': 'بخش ها',
			'thetastart': 'شروع تتا',
			'thetalength': 'طول تتا',

			'radiustop': 'شعاع بالا',
			'radiusbottom': 'شعاع پایین',
			'radialsegments': 'بخش های شعاعی',
			'heightsegments': 'بخش های ارتفاع',
			'openended': 'پایان باز',

			'curveSegments': 'بخش های منحنی',
			'steps': 'گام ها',
			'bevelEnabled': 'اریب',
			'bevelThickness': 'ضخامت',
			'bevelSize': 'سایز',
			'bevelOffset': 'افست',
			'bevelSegments': 'بخش ها',
			'shape': 'تبدیل به شکل',

			'detail': 'جزییات',

			'phistart': 'شروع فی (°)',
			'philength': 'طول فی (°)',
			'points': 'امتیاز ها',

			'widthsegments': 'بخش عرض',

			'innerRadius': 'شعاع داخلی',
			'outerRadius': 'شعاع خارجی',
			'thetaSegments': 'بخش های تتا',
			'phiSegments': 'بخش های فی',

			'extrude': 'اکسترود کردن',

			'tubularsegments': 'بخش های لوله ای',
			'arc': 'آرک',

			'p': 'P',
			'q': 'Q',

			'path': 'مسیر',
			'closed': 'بسته شده',
			'curvetype': 'نوع انحنا',
			'tension': 'تنش',

			'copy': 'کپی',
			'paste': 'پیست',
			'slot': 'شکاف',
			'program': 'برنامه',
			'info': 'اطلاعات',
			'vertex': 'راس',
			'fragment': 'فرگ',
			'depthPacking': 'بسته بندی عمق',
			'roughness': 'زبری',
			'metalness': 'فلزی بودن',
			'reflectivity': 'انعکاس',
			'emissive': 'پرتاب کنندگی',
			'specular': 'اسپکولار',
			'shininess': 'درخشندگی',
			'clearcoat': 'کلیرکت',
			'clearcoatroughness': 'زبری کلیرکت',
			'dispersion': 'پراکندگی',
			'ior': 'IOR',
			'iridescence': 'رنگین کمانی',
			'iridescenceIOR': 'IOR تین فیلم',
			'iridescenceThicknessMax': 'زبری تین فیلم',
			'sheen': 'درخشش (شین)',
			'sheenroughness': 'زبری درخشش (شین)',
			'sheencolor': 'رنگ درخشش (شین)',
			'transmission': 'انتقال',
			'attenuationDistance': 'تضعیف فاصله',
			'attenuationColor': 'تضعیف رنگ',
			'thickness': 'ضخامت',
			'vertexcolors': 'رنگ راس ها',
			'matcap': 'متکپ',
			'map': 'مپ',
			'alphamap': 'مپ آلفا',
			'bumpmap': 'مپ بامپ',
			'normalmap': 'مپ نرمال',
			'clearcoatmap': 'مپ کلیرکت',
			'clearcoatnormalmap': 'مپ معمولی کلیرکت',
			'clearcoatroughnessmap': 'مپ زبری کلیرکت',
			'displacementmap': 'مپ جابجایی',
			'roughnessmap': 'مپ زبری',
			'metalnessmap': 'مپ فلزی بودن',
			'specularmap': 'مپ اسپکولار',
			'iridescencemap': 'مپ رنگین کمانی',
			'iridescencethicknessmap': 'مپ ضخامت تین فیلم',
			'sheencolormap': 'مپ رنگ درخشش (شین)',
			'sheenroughnessmap': 'مپ زبری شین',
			'envmap': 'مپ محیط',
			'lightmap': 'مپ نور',
			'aomap': 'AO مپ',
			'emissivemap': 'مپ پرتاب کننده',
			'gradientmap': 'مپ گردینت',
			'transmissionmap': 'مپ انتقال',
			'thicknessmap': 'مپ ضخامت',
			'side': 'سمت',
			'size': 'سایز',
			'sizeAttenuation': 'تضعیف سایز',
			'flatShading': 'سایه زنی تخت',
			'blending': 'مخلوط کردن',
			'opacity': 'کدر بودن',
			'transparent': 'شفاف',
			'forcesinglepass': 'فورس سینگل پس',
			'alphatest': 'تست آلفا',
			'depthtest': 'تست عمق',
			'depthwrite': 'نوشتن عمق',
			'wireframe': 'وایرفریم',
			'remove': 'حذف',

			'project': 'پروژه ها',
			'antialias': 'آنتی الآیس',
			'shadows': 'سایه ها',
			'toneMapping': 'تون مپینگ',
			'materials': 'متریال ها',
			'Assign': 'اختصاص',

			'app': 'اپ',
			'title': 'تیتر',
			'editable': 'قابل ویرایش',
			'publish': 'انتشار',

			'image': 'عکس',
			'samples': 'نمونه ها',
			'video': 'ویدیو',

			'shading': 'سایه زنی',
			'resolution': 'وضوح',
			'duration': 'مدت',
			'render': 'رندر',

			'settings': 'تنظیمات',
			'language': 'زبان ها',

			'shortcuts': 'شورت کات ها',
			'translate': 'ترجمه',
			'rotate': 'چرخش (دوران)',
			'focus': 'فوکوس',

			'history': 'هیستوری',
			'clear': 'پاک کردن',
			'persistent': 'ماندگار',

			'local': 'لوکال',

			'grid': 'گرید',
			'helpers': 'کمک کننده',

			'objects': 'آبجکت ها',
			'vertices': 'رئوس',
			'triangle': 'مثلث',
			'triangles': 'مثلث ها',
			'sample': 'نمونه',
			'rendertime': 'زمان رندر',

			'vertexShader': 'شیدر راس',
			'fragmentShader': 'شیدر فرگمنت',
			'programInfo': 'خواص برنامه'

		},
		'en': {
			'prompt/open': 'Any unsaved data will be lost. Are you sure?',
			'prompt/file/failedToOpenProject': 'Failed to open project!',
			'prompt/export/noMeshSelected': 'No Mesh selected!',
			'prompt/export/noObjectSelected': 'No Object selected!',
			'prompt/remove': 'Are you sure?',
			'prompt/clear': 'The Undo/Redo History will be cleared. Are you sure?',
			'prompt/preserve': 'The history will be preserved across sessions.\nThis can have an impact on performance when working with textures.',
			'prompt/forbid': 'Undo/Redo disabled while scene is playing.',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC Shading: Only MeshStandardMaterial and MeshPhysicalMaterial are supported',

			'AddObject': 'Add Object',
			'AddScript': 'Add Script',
			'MoveObject': 'Move Object',
			'MultiCmds': 'Multiple Changes',
			'RemoveObject': 'Remove Object',
			'RemoveScript': 'Remove Script',
			'SetColor': 'Set Color',
			'SetGeometry': 'Set Geometry',
			'SetGeometryValue': 'Set Geometry Value',
			'SetMaterialColor': 'Set Material Color',
			'SetMaterial': 'Set Material',
			'SetMaterialMap': 'Set Material Map',
			'SetMaterialRange': 'Set Material Range',
			'SetMaterialValue': 'Set Material Value',
			'SetMaterialVector': 'Set Material Vector',
			'SetPosition': 'Set Position',
			'SetRotation': 'Set Rotation',
			'SetScale': 'Set Scale',
			'SetScene': 'Set Scene',
			'SetScriptValue': 'Set Script Value',
			'SetShadowValue': 'Set Shadow Value',
			'SetUuid': 'Set UUID',
			'SetValue': 'Set Value',

			'file': 'File',
			'new': 'New',
			'empty': 'Empty',
			'arkanoid': 'Arkanoid',
			'camera': 'Camera',
			'particles': 'Particles',
			'new/Pong': 'Pong',
			'shaders': 'Shaders',
			'open': 'Open',
			'save': 'Save',
			'import': 'Import',
			'export': 'Export',

			'edit': 'Edit',
			'undo': 'Undo',
			'redo': 'Redo',
			'center': 'Center',
			'clone': 'Clone',
			'delete': 'Delete',

			'add': 'Add',
			'group': 'Group',

			'mesh': 'Mesh',
			'plane': 'Plane',
			'box': 'Box',
			'capsule': 'Capsule',
			'circle': 'Circle',
			'cylinder': 'Cylinder',
			'ring': 'Ring',
			'sphere': 'Sphere',
			'dodecahedron': 'Dodecahedron',
			'icosahedron': 'Icosahedron',
			'octahedron': 'Octahedron',
			'tetrahedron': 'Tetrahedron',
			'torus': 'Torus',
			'tube': 'Tube',
			'torusknot': 'TorusKnot',
			'lathe': 'Lathe',
			'sprite': 'Sprite',

			'light': 'Light',
			'ambient': 'Ambient',
			'directional': 'Directional',
			'hemisphere': 'Hemisphere',
			'point': 'Point',
			'spot': 'Spot',

			'perspective': 'Perspective',
			'orthographic': 'Orthographic',

			'autosave': 'autosave',

			'view': 'View',
			'fullscreen': 'Fullscreen',
			'gridHelper': 'Grid Helper',
			'cameraHelpers': 'Camera Helpers',
			'lightHelpers': 'Light Helpers',
			'skeletonHelpers': 'Skeleton Helpers',

			'help': 'Help',
			'source_code': 'Source Code',
			'icons': 'Icon Pack',
			'about': 'About',
			'manual': 'Manual',

			'animations': 'Animations',
			'play': 'Play',
			'stop': 'Stop',
			'timecale': 'Time Scale',

			'scene': 'Scene',
			'background': 'Background',
			'environment': 'Environment',
			'fog': 'Fog',

			'object': 'Object',
			'geometry': 'Geometry',
			'material': 'Material',
			'script': 'Script',

			'type': 'Type',
			'uuid': 'UUID',
			'name': 'Name',
			'position': 'Position',
			'rotation': 'Rotation',
			'scale': 'Scale',
			'fov': 'Fov',
			'left': 'Left',
			'right': 'Right',
			'top': 'Top',
			'bottom': 'Bottom',
			'near': 'Near',
			'far': 'Far',
			'intensity': 'Intensity',
			'color': 'Color',
			'groundcolor': 'Ground Color',
			'distance': 'Distance',
			'angle': 'Angle',
			'penumbra': 'Penumbra',
			'decay': 'Decay',
			'shadow': 'Shadow',
			'shadowIntensity': 'Shadow Intensity',
			'shadowBias': 'Shadow Bias',
			'shadowNormalBias': 'Shadow Normal Bias',
			'shadowRadius': 'Shadow Radius',
			'cast': 'cast',
			'receive': 'receive',
			'visible': 'Visible',
			'frustumcull': 'Frustum Cull',
			'renderorder': 'Render Order',
			'userdata': 'User data',
			'exportjson': 'Export JSON',

			'geometry/type': 'Type',
			'geometry/new': 'New',
			'geometry/uuid': 'UUID',
			'geometry/name': 'Name',
			'geometry/bounds': 'Bounds',
			'geometry/userdata': 'User Data',
			'geometry/show_vertex_normals': 'Show Vertex Normals',
			'geometry/compute_vertex_normals': 'Compute Vertex Normals',
			'geometry/compute_vertex_tangents': 'Compute Tangents',
			'geometry/center': 'Center',
			'geometry/export': 'Export JSON',

			'width': 'Width',
			'height': 'Height',
			'depth': 'Depth',
			'widthseg': 'Width Seg',
			'heightseg': 'Height Seg',
			'depthseg': 'Depth Seg',

			'attributes': 'Attributes',
			'index': 'index',
			'morphAttributes': 'Morph Attributes',
			'morphRelative': 'Morph Relative',

			'radius': 'Radius',
			'capseg': 'Cap Seg',
			'radialseg': 'Radial Seg',

			'segments': 'Segments',
			'thetastart': 'Theta start',
			'thetalength': 'Theta length',

			'radiustop': 'Radius top',
			'radiusbottom': 'Radius bottom',
			'radialsegments': 'Radial segments',
			'heightsegments': 'Height segments',
			'openended': 'Open ended',

			'curveSegments': 'Curve Segments',
			'steps': 'Steps',
			'bevelEnabled': 'Bevel',
			'bevelThickness': 'Thickness',
			'bevelSize': 'Size',
			'bevelOffset': 'Offset',
			'bevelSegments': 'Segments',
			'shape': 'Convert to Shape',

			'detail': 'Detail',
			'phistart': 'Phi start (°)',
			'philength': 'Phi length (°)',
			'points': 'Points',
			'widthsegments': 'Width segments',
			'innerRadius': 'Inner radius',
			'outerRadius': 'Outer radius',
			'thetaSegments': 'Theta segments',
			'phiSegments': 'Phi segments',
			'extrude': 'Extrude',
			'tubularsegments': 'Tubular segments',
			'arc': 'Arc',
			'p': 'P',
			'q': 'Q',

			'path': 'Path',
			'closed': 'Closed',
			'curvetype': 'Curve Type',
			'tension': 'Tension',

			'copy': 'Copy',
			'paste': 'Paste',
			'slot': 'Slot',
			'program': 'Program',
			'info': 'Info',
			'vertex': 'Vert',
			'fragment': 'Frag',
			'depthPacking': 'Depth Packing',
			'roughness': 'Roughness',
			'metalness': 'Metalness',
			'reflectivity': 'Reflectivity',
			'emissive': 'Emissive',
			'specular': 'Specular',
			'shininess': 'Shininess',
			'clearcoat': 'Clearcoat',
			'clearcoatroughness': 'Clearcoat Roughness',
			'dispersion': 'Dispersion',
			'ior': 'IOR',
			'iridescence': 'Iridescence',
			'iridescenceIOR': 'Thin-Film IOR',
			'iridescenceThicknessMax': 'Thin-Film Thickness',
			'sheen': 'Sheen',
			'sheenroughness': 'Sheen Roughness',
			'sheencolor': 'Sheen Color',
			'transmission': 'Transmission',
			'attenuationDistance': 'Attenuation Distance',
			'attenuationColor': 'Attenuation Color',
			'thickness': 'Thickness',
			'vertexcolors': 'Vertex Colors',
			'matcap': 'Matcap',
			'map': 'Map',
			'alphamap': 'Alpha Map',
			'bumpmap': 'Bump Map',
			'normalmap': 'Normal Map',
			'clearcoatmap': 'Clearcoat Map',
			'clearcoatnormalmap': 'Clearcoat Normal Map',
			'clearcoatroughnessmap': 'Clearcoat Roughness Map',
			'displacementmap': 'Displace Map',
			'roughnessmap': 'Rough. Map',
			'metalnessmap': 'Metal. Map',
			'specularmap': 'Specular Map',
			'iridescencemap': 'Irid. Map',
			'iridescencethicknessmap': 'Thin-Film Thickness Map',
			'sheencolormap': 'Sheen Color Map',
			'sheenroughnessmap': 'Sheen Rough. Map',
			'envmap': 'Env Map',
			'lightmap': 'Light Map',
			'aomap': 'AO Map',
			'emissivemap': 'Emissive Map',
			'gradientmap': 'Gradient Map',
			'transmissionmap': 'Transmission Map',
			'thicknessmap': 'Thickness Map',
			'side': 'Side',
			'size': 'Size',
			'sizeAttenuation': 'Size Attenuation',
			'flatShading': 'Flat Shading',
			'blending': 'Blending',
			'opacity': 'Opacity',
			'transparent': 'Transparent',
			'forcesinglepass': 'Force Single Pass',
			'alphatest': 'Alpha Test',
			'depthtest': 'Depth Test',
			'depthwrite': 'Depth Write',
			'wireframe': 'Wireframe',
			'remove': 'Remove',

			'project': 'Project',
			'antialias': 'Antialias',
			'shadows': 'Shadows',
			'toneMapping': 'Tonemapping',
			'materials': 'Materials',
			'Assign': 'Assign',

			'app': 'App',
			'title': 'Title',
			'editable': 'Editable',
			'publish': 'Publish',

			'image': 'Image',
			'samples': 'Samples',
			'video': 'Video',

			'shading': 'Shading',
			'resolution': 'Resolution',
			'duration': 'Duration',
			'render': 'Render',

			'settings': 'Settings',
			'language': 'Language',

			'shortcuts': 'Shortcuts',
			'translate': 'Translate',
			'rotate': 'Rotate',
			'focus': 'Focus',

			'history': 'History',
			'clear': 'Clear',
			'persistent': 'Persistent',

			'local': 'Local',

			'grid': 'Grid',
			'helpers': 'Helpers',

			'objects': 'Objects',
			'vertices': 'Vertices',
			'triangle': 'Triangle',
			'triangles': 'Triangles',
			'sample': 'Sample',
			'rendertime': 'Render time',

			'vertexShader': 'Vertex Shader',
			'fragmentShader': 'Fragment Shader',
			'programInfo': 'Program Properties'

		},

		'fr': {

			'prompt/open': 'Toutes les données non enregistrées seront perdues Êtes-vous sûr ?',
			'prompt/file/failedToOpenProject': 'Échec de l\'ouverture du projet !',
			'prompt/export/noMeshSelected': 'Aucun maillage sélectionné !',
			'prompt/export/noObjectSelected': 'Aucun objet sélectionné !',
			'prompt/remove': 'Es-tu sûr?',
			'prompt/clear': 'L\'historique d\'annulation/rétablissement sera effacé Êtes-vous sûr ?',
			'prompt/preserve': 'L\'histoire sera conservée entre les sessions.\nCela peut avoir un impact sur les performances lors de la manipulation des textures.',
			'prompt/forbid': 'Les fonctions Annuler/Rétablir sont désactivées pendant la lecture de la scène.',
			'prompt/rendering/realistic/unsupportedMaterial': 'Ombrage REALISTIC : seuls MeshStandardMaterial et MeshPhysicalMaterial sont pris en charge',

			'AddObject': 'Ajouter un objet',
			'AddScript': 'Ajouter un script',
			'MoveObject': 'Déplacer l’objet',
			'MultiCmds': 'Changements multiples',
			'RemoveObject': 'Supprimer l’objet',
			'RemoveScript': 'Supprimer le script',
			'SetColor': 'Définir la couleur',
			'SetGeometry': 'Définir la géométrie',
			'SetGeometryValue': 'Définir la valeur de la géométrie',
			'SetMaterialColor': 'Définir la couleur du matériau',
			'SetMaterial': 'Matériel de l’ensemble',
			'SetMaterialMap': 'Définir la carte des matériaux',
			'SetMaterialRange': 'Définir la gamme de matériaux',
			'SetMaterialValue': 'Définir la valeur du matériau',
			'SetMaterialVector': 'Définir le vecteur de matériau',
			'SetPosition': 'Définir la position',
			'SetRotation': 'Définir la rotation',
			'SetScale': 'Définir l’échelle',
			'SetScene': 'Planter le décor',
			'SetScriptValue': 'Définir la valeur du script',
			'SetShadowValue': 'Set Shadow Value',
			'SetUuid': 'Définir l’UUID',
			'SetValue': 'Définir la valeur',

			'file': 'Fichier',
			'new': 'Nouveau',
			'empty': 'Vide',
			'arkanoid': 'Arkanoid',
			'camera': 'Camera',
			'particles': 'Particles',
			'new/Pong': 'Pong',
			'shaders': 'Shaders',
			'open': 'Open',
			'save': 'Save',
			'import': 'Importer',
			'export': 'Exporter',

			'edit': 'Edition',
			'undo': 'Annuler',
			'redo': 'Refaire',
			'center': 'Center',
			'clone': 'Cloner',
			'delete': 'Supprimer',

			'add': 'Ajouter',
			'group': 'Groupe',

			'mesh': 'Maille',
			'plane': 'Plan',
			'box': 'Cube',
			'capsule': 'Capsule',
			'circle': 'Cercle',
			'cylinder': 'Cylindre',
			'ring': 'Bague',
			'sphere': 'Sphère',
			'dodecahedron': 'Dodécaèdre',
			'icosahedron': 'Icosaèdre',
			'octahedron': 'Octaèdre',
			'tetrahedron': 'Tétraèdre',
			'torus': 'Torus',
			'tube': 'Tube',
			'torusknot': 'Noeud Torus',
			'lathe': 'Tour',
			'sprite': 'Sprite',

			'light': 'Lumière',
			'ambient': 'Ambiante',
			'directional': 'Directionnelle',
			'hemisphere': 'Hémisphérique',
			'point': 'Ponctuelle',
			'spot': 'Projecteur',

			'perspective': 'Perspective',
			'orthographic': 'Orthographique',

			'autosave': 'enregistrement automatique',

			'view': 'View',
			'fullscreen': 'Fullscreen',
			'gridHelper': 'Assistant de grille',
			'cameraHelpers': 'Aides à la caméra',
			'lightHelpers': 'Aides Lumière',
			'skeletonHelpers': 'Aides squelettes',

			'help': 'Aide',
			'source_code': 'Code Source',
			'icons': 'Icon Pack',
			'about': 'A propos',
			'manual': 'Manual',

			'animations': 'Animations',
			'play': 'Play',
			'stop': 'Stop',
			'timescale': 'Time Scale',

			'scene': 'Scène',
			'background': 'Arrière Plan',
			'environment': 'Environment',
			'fog': 'Brouillard',

			'object': 'Objet',
			'geometry': 'Géométrie',
			'material': 'Matériaux',
			'script': 'Script',

			'type': 'Type',
			'uuid': 'UUID',
			'name': 'Nom',
			'position': 'Position',
			'rotation': 'Rotation',
			'scale': 'Échelle',
			'fov': 'Champ de vision',
			'left': 'Gauche',
			'right': 'Droite',
			'top': 'Haut',
			'bottom': 'Bas',
			'near': 'Près',
			'far': 'Loin',
			'intensity': 'Intensité',
			'color': 'Couleur',
			'groundcolor': 'Couleur de fond',
			'distance': 'Distance',
			'angle': 'Angle',
			'penumbra': 'Pénombre',
			'decay': 'Affaiblissement',
			'shadow': 'Ombre',
			'shadowIntensity': 'Shadow Intensity',
			'shadowBias': 'Biais directionnel des ombres',
			'shadowNormalBias': 'Shadow Normal Bias',
			'shadowRadius': 'Rayon de l\'ombre',
			'cast': 'Projète',
			'receive': 'Reçoit',
			'visible': 'Visible',
			'frustumcull': 'Culling',
			'renderorder': 'Ordre de rendus',
			'userdata': 'Données utilisateur',
			'exportjson': 'Exporter JSON',

			'geometry/type': 'Type',
			'geometry/new': 'Nouveau',
			'geometry/uuid': 'UUID',
			'geometry/name': 'Nom',
			'geometry/bounds': 'Limites',
			'geometry/userdata': 'Données utilisateur',
			'geometry/show_vertex_normals': 'Afficher normales',
			'geometry/compute_vertex_normals': 'Compute Vertex Normals',
			'geometry/compute_vertex_tangents': 'Compute Tangents',
			'geometry/center': 'Center',
			'geometry/export': 'Exporter JSON',

			'width': 'Largeur',
			'height': 'Hauteur',
			'depth': 'Profondeur',
			'widthseg': 'Segments en Largeur',
			'heightseg': 'Segments en Hauteur',
			'depthseg': 'Segments en Profondeur',

			'attributes': 'Attributs',
			'index': 'index',
			'morphAttributes': 'Morph Attributes',
			'morphRelative': 'Morph Relative',

			'radius': 'Radius',
			'capseg': 'Cap Seg',
			'radialseg': 'Radial Seg',

			'segments': 'Segments',
			'thetastart': 'Début Thêta (°)',
			'thetalength': 'Longueur Thêta (°)',

			'radiustop': 'Rayon supérieur',
			'radiusbottom': 'Rayon inférieur',
			'radialsegments': 'Segments radiaux',
			'heightsegments': 'Segments en hauteur',
			'openended': 'Extrémités ouvertes',

			'curveSegments': 'Segments de courbe',
			'steps': 'Pas',
			'bevelEnabled': 'Biseau',
			'bevelThickness': 'Épaisseur',
			'bevelSize': 'Taille',
			'bevelOffset': 'Décalage',
			'bevelSegments': 'Segments',
			'shape': 'Convertir en forme',

			'detail': 'Détail',

			'phistart': 'Début Phi (°)',
			'philength': 'Longueur Phi (°)',
			'points': 'Points',

			'widthsegments': 'Segments en Largeur',

			'innerRadius': 'Rayon intérieur',
			'outerRadius': 'Rayon extérieur',
			'thetaSegments': 'Segments Thêta',
			'phiSegments': 'Phi segments',

			'extrude': 'Extruder',

			'tubularsegments': 'Segments tubulaires',
			'arc': 'Arc',

			'p': 'P',
			'q': 'Q',

			'path': 'Chemin',
			'closed': 'Fermé',
			'curvetype': 'Type de courbe',
			'tension': 'Tension',

			'copy': 'Copier',
			'paste': 'Coller',
			'slot': 'Slot',
			'program': 'Programme',
			'info': 'Info',
			'vertex': 'Sommet',
			'fragment': 'Fragment',
			'depthPacking': 'Encodage profondeur de couleur',
			'roughness': 'Rugosité',
			'metalness': 'Métal',
			'reflectivity': 'Reflectivity',
			'emissive': 'Émissif',
			'specular': 'Spéculaire',
			'shininess': 'Brillance',
			'clearcoat': 'Vernis',
			'clearcoatroughness': 'Rugosité du vernis',
			'dispersion': 'Dispersion',
			'ior': 'IOR',
			'iridescence': 'Iridescence',
			'iridescenceIOR': 'Thin-Film IOR',
			'iridescenceThicknessMax': 'Thin-Film Thickness',
			'sheen': 'Sheen',
			'sheenroughness': 'Sheen Roughness',
			'sheencolor': 'Sheen Color',
			'transmission': 'Transmission',
			'attenuationDistance': 'Attenuation Distance',
			'attenuationColor': 'Attenuation Color',
			'thickness': 'Thickness',
			'vertexcolors': 'Couleurs aux Sommets',
			'matcap': 'Matcap',
			'map': 'Texture',
			'alphamap': 'Texture de transparence',
			'bumpmap': 'Texture de relief',
			'normalmap': 'Texture de normales',
			'clearcoatmap': 'Clearcoat Map',
			'clearcoatnormalmap': 'Texture des normales du vernis',
			'clearcoatroughnessmap': 'Clearcoat Roughness Map',
			'displacementmap': 'Texture de déplacement',
			'roughnessmap': 'Texture de rugosité',
			'metalnessmap': 'Texture métallique',
			'specularmap': 'Texture spéculaire',
			'iridescencemap': 'Irid. Map',
			'iridescencethicknessmap': 'Thin-Film Thickness Map',
			'sheencolormap': 'Sheen Color Map',
			'sheenroughnessmap': 'Sheen Rough. Map',
			'envmap': 'Texture d\'environnement',
			'lightmap': 'Texture d\'éclairage',
			'aomap': 'Texture d\'occlusion ambiante',
			'emissivemap': 'Texture d\'émission',
			'gradientmap': 'Texture de gradient',
			'transmissionmap': 'Transmission Map',
			'thicknessmap': 'Thickness Map',
			'side': 'Côté',
			'size': 'Size',
			'sizeAttenuation': 'Size Attenuation',
			'flatShading': 'Flat Shading',
			'blending': 'Mélange',
			'opacity': 'Opacité',
			'transparent': 'Transparence',
			'forcesinglepass': 'Force Single Pass',
			'alphatest': 'Test de transparence',
			'depthtest': 'Depth Test',
			'depthwrite': 'Depth Write',
			'wireframe': 'Fil de fer',
			'remove': 'Supprimer',

			'project': 'Projet',
			'antialias': 'Anticrénelage',
			'shadows': 'Ombres',
			'toneMapping': 'Mappage des nuances',
			'materials': 'Matériaux',
			'Assign': 'Attribuer',

			'app': 'App',
			'title': 'Titre',
			'editable': 'Modifiable',
			'publish': 'Publier',

			'image': 'Image',
			'samples': 'd\'échantillons',
			'video': 'Video',

			'shading': 'Shading',
			'resolution': 'Resolution',
			'duration': 'Duration',
			'render': 'Render',

			'settings': 'Paramètres',
			'language': 'Langue',

			'shortcuts': 'Shortcuts',
			'translate': 'Position',
			'rotate': 'Rotation',
			'focus': 'Focus',

			'history': 'Historique',
			'clear': 'Supprimer',
			'persistent': 'Permanent',

			'local': 'Local',

			'grid': 'Grille',
			'helpers': 'Helpers',

			'objects': 'Objets',
			'vertices': 'Sommets',
			'triangle': 'Triangle',
			'triangles': 'Triangles',
			'sample': 'Échantillon',
			'rendertime': 'Temps de rendu',

			'vertexShader': 'Vertex Shader',
			'fragmentShader': 'Fragment Shader',
			'programInfo': 'Propriétés du programme'

		},

		'zh': {

			'prompt/open': '您确定吗？未保存的数据将会丢失。',
			'prompt/file/failedToOpenProject': '无法打开项目！',
			'prompt/export/noMeshSelected': '未选择网格！',
			'prompt/export/noObjectSelected': '未选择对象！',
			'prompt/remove': '你确定吗？',
			'prompt/clear': '撤销/重做历史记录将被清除。您确定吗？',
			'prompt/preserve': '历史将在会话之间保留。\n这可能会影响在处理纹理时的性能。',
			'prompt/forbid': '在播放场景时，撤消/重做被禁用。',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC着色：仅支持 MeshStandardMaterial 和 MeshPhysicalMaterial',

			'AddObject': '添加对象',
			'AddScript': '添加脚本',
			'MoveObject': '移动对象',
			'MultiCmds': '多次更改',
			'RemoveObject': '删除对象',
			'RemoveScript': '删除脚本',
			'SetColor': '设置颜色',
			'SetGeometry': '设置几何图形',
			'SetGeometryValue': '设置几何值',
			'SetMaterialColor': '设置材质颜色',
			'SetMaterial': '设置材质',
			'SetMaterialMap': '设置材质贴图',
			'SetMaterialRange': '设置材料范围',
			'SetMaterialValue': '设置材料值',
			'SetMaterialVector': '设置材质矢量',
			'SetPosition': '设置位置',
			'SetRotation': '设置旋转',
			'SetScale': '设置比例',
			'SetScene': '设置布景',
			'SetScriptValue': '设置脚本值',
			'SetShadowValue': '设置阴影值',
			'SetUuid': '设置 UUID',
			'SetValue': '设定值',

			'file': '文件',
			'new': '新建项目',
			'empty': '空',
			'arkanoid': '打砖块',
			'camera': ' 摄像机',
			'particles': '粒子',
			'new/Pong': '乒乓球',
			'shaders': '着色器',
			'open': '打开',
			'save': '保存',
			'import': '导入',
			'export': '导出',

			'edit': '编辑',
			'undo': '撤销',
			'redo': '重做',
			'center': '居中',
			'clone': '拷贝',
			'delete': '删除',

			'add': '添加',
			'group': '组',

			'mesh': '网格',
			'plane': '平面',
			'box': '正方体',
			'capsule': '胶囊',
			'circle': '圆',
			'cylinder': '圆柱体',
			'ring': '环',
			'sphere': '球体',
			'dodecahedron': '十二面体',
			'icosahedron': '二十面体',
			'octahedron': '八面体',
			'tetrahedron': '四面体',
			'torus': '圆环体',
			'torusknot': '环面纽结体',
			'tube': '管',
			'lathe': '酒杯',
			'sprite': '精灵',

			'light': '光源',
			'ambient': '环境光',
			'directional': '平行光',
			'hemisphere': '半球光',
			'point': '点光源',
			'spot': '聚光灯',

			'perspective': '透视相机',
			'orthographic': '正交相机',

			'autosave': '自动保存',

			'view': '视图',
			'fullscreen': '全屏',
			'gridHelper': '网格助手',
			'cameraHelpers': '相机助手',
			'lightHelpers': '光助手',
			'skeletonHelpers': '骷髅助手',

			'help': '帮助',
			'source_code': '源码',
			'icons': '图标组件包',
			'about': '关于',
			'manual': '手册',

			'animations': '动画',
			'play': '播放',
			'stop': '暂停',
			'timescale': '时间缩放',

			'scene': '场景',
			'background': '背景',
			'environment': '环境',
			'fog': '雾',

			'object': '属性',
			'geometry': '几何组件',
			'material': '材质组件',
			'script': '脚本',

			'type': '类型',
			'uuid': '识别码',
			'name': '名称',
			'position': '位置',
			'rotation': '旋转',
			'scale': '缩放',
			'fov': '视角',
			'left': '左',
			'right': '右',
			'top': '上',
			'bottom': '下',
			'near': '近点',
			'far': '远点',
			'intensity': '强度',
			'color': '颜色',
			'groundcolor': '基色',
			'distance': '距离',
			'angle': '角度',
			'penumbra': '边缘',
			'decay': '衰减',
			'shadow': '阴影',
			'shadowIntensity': '阴影强度',
			'shadowBias': '阴影偏移',
			'shadowNormalBias': '阴影法线偏移',
			'shadowRadius': '阴影半径',
			'cast': '产生',
			'receive': '接受',
			'visible': '可见性',
			'frustumcull': '视锥体裁剪',
			'renderorder': '渲染次序',
			'userdata': '自定义数据',
			'exportjson': '导出JSON',

			'geometry/type': '类型',
			'geometry/new': '更新',
			'geometry/uuid': '识别码',
			'geometry/name': '名称',
			'geometry/bounds': '界限',
			'geometry/userdata': '自定义数据',
			'geometry/show_vertex_normals': '显示顶点法线',
			'geometry/compute_vertex_normals': '计算顶点法线',
			'geometry/compute_vertex_tangents': '计算切线',
			'geometry/center': '居中',
			'geometry/export': '导出JSON',

			'width': '宽度',
			'height': '高度',
			'depth': '深度',
			'widthseg': '宽度分段',
			'heightseg': '高度分段',
			'depthseg': '深度分段',

			'attributes': '属性',
			'index': '索引',
			'morphAttributes': '变形属性',
			'morphRelative': '相对变形',

			'radius': '半径',
			'capseg': '胶囊分段',
			'radialseg': '半径分段',

			'segments': '分段',
			'thetastart': '弧度起点',
			'thetalength': '弧度长度',

			'radiustop': '顶部半径',
			'radiusbottom': '底部半径',
			'radialsegments': '径向分段',
			'heightsegments': '高度分段',
			'openended': '开端',

			'curveSegments': '曲线段',
			'steps': '细分点数',
			'bevelEnabled': '启用斜角',
			'bevelThickness': '斜角厚度',
			'bevelSize': '斜角大小',
			'bevelOffset': '斜角偏移量',
			'bevelSegments': '斜角分段',
			'shape': '转换图形',

			'detail': '面片分段',

			'phistart': '经度起点',
			'philength': '经度长度',
			'points': '点',

			'widthsegments': '宽度分段',

			'innerRadius': '内半径',
			'outerRadius': '外半径',
			'thetaSegments': '弧度分段',
			'phiSegments': '经度分段',

			'extrude': '拉伸',

			'tubularsegments': '管厚分段',
			'arc': '弧度',

			'p': '管长弧度',
			'q': '扭曲弧度',

			'path': '路径',
			'closed': '闭合',
			'curvetype': '曲线类型',
			'tension': '张力',

			'copy': '复制',
			'paste': '粘贴',
			'slot': '插槽',
			'program': '程序',
			'info': '信息',
			'vertex': '顶点',
			'fragment': '片元',
			'depthPacking': '深度包装',
			'roughness': '粗糙度',
			'metalness': '金属度',
			'reflectivity': '反射率',
			'emissive': '自发光',
			'specular': '高光',
			'shininess': '高光大小',
			'clearcoat': '清漆',
			'clearcoatroughness': '清漆粗糙度',
			'dispersion': '分散',
			'ior': 'IOR',
			'iridescence': '彩虹色',
			'iridescenceIOR': '彩虹色折射率',
			'iridescenceThicknessMax': '彩虹色厚度',
			'sheen': '光泽',
			'sheenroughness': '光泽粗糙度',
			'sheencolor': '光泽颜色',
			'transmission': '透光',
			'attenuationDistance': '衰减距离',
			'attenuationColor': '衰减色',
			'thickness': '厚度',
			'vertexcolors': '顶点颜色',
			'matcap': '材质捕获',
			'map': '贴图',
			'alphamap': '透明贴图',
			'bumpmap': '凹凸贴图',
			'normalmap': '法线贴图',
			'clearcoatmap': '清漆贴图',
			'clearcoatnormalmap': '清漆法线贴图',
			'clearcoatroughnessmap': '清漆粗糙度贴图',
			'displacementmap': '置换贴图',
			'roughnessmap': '粗糙度贴图',
			'metalnessmap': '金属贴图',
			'specularmap': '高光贴图',
			'iridescencemap': '彩虹色贴图',
			'iridescencethicknessmap': '彩虹色厚度贴图',
			'sheencolormap': '光泽颜色贴图',
			'sheenroughnessmap': '光泽粗糙度贴图',
			'envmap': '环境贴图',
			'lightmap': '光照贴图',
			'aomap': '环境光遮蔽贴图',
			'emissivemap': '自发光贴图',
			'gradientmap': '渐变贴图',
			'transmissionmap': '透光贴图',
			'thicknessmap': '厚度贴图',
			'side': '面',
			'size': '大小',
			'sizeAttenuation': '大小衰减',
			'flatShading': '平面着色',
			'blending': '混合',
			'opacity': '透明度',
			'transparent': '透明性',
			'forcesinglepass': '强制单通道',
			'alphatest': 'α测试',
			'depthtest': '深度测试',
			'depthwrite': '深度缓冲',
			'wireframe': '线框',
			'remove': '删除',

			'project': '项目',
			'antialias': '抗锯齿',
			'shadows': '阴影',
			'toneMapping': '色调映射',
			'materials': '材质',
			'Assign': '应用',

			'app': 'App',
			'title': '标题',
			'editable': '编辑性',
			'publish': '发布',

			'image': '图片',
			'samples': '样本',
			'video': '视频',

			'shading': '阴影',
			'resolution': '分辨率',
			'duration': '时长',
			'render': '渲染',

			'settings': '设置',
			'language': '语言',

			'shortcuts': '快捷键',
			'translate': '移动',
			'rotate': '旋转',
			'focus': '聚焦',

			'history': '历史记录',
			'clear': '清空',
			'persistent': '本地存储',

			'local': '本地',

			'grid': '网格',
			'helpers': '辅助',

			'objects': '物体',
			'vertices': '顶点',
			'triangle': '三角形',
			'triangles': '三角形',
			'sample': '样本',
			'rendertime': '渲染时间',

			'vertexShader': '顶点着色器',
			'fragmentShader': '片段着色器',
			'programInfo': '程序属性'

		},

		'ja': {

			'prompt/open': '保存されていないデータは失われます。 本気ですか？',
			'prompt/file/failedToOpenProject': 'プロジェクトを開くことができませんでした!',
			'prompt/export/noMeshSelected': 'メッシュが選択されていません!',
			'prompt/export/noObjectSelected': 'オブジェクトが選択されていません!',
			'prompt/remove': '本気ですか？',
			'prompt/clear': '元に戻す/やり直しの履歴が消去されます。 本気ですか？',
			'prompt/preserve': '履歴はセッションをまたいで保存されます。\nこれは、テクスチャを操作する際のパフォーマンスに影響を与える可能性があります。',
			'prompt/forbid': 'シーンの再生中は元に戻す/やり直しは無効になります。',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC シェーディング: MeshStandardmaterial と MeshPhysicalmaterial のみがサポートされています',

			'AddObject': 'オブジェクトを追加',
			'AddScript': 'スクリプトを追加',
			'MoveObject': 'オブジェクトの移動',
			'MultiCmds': '複数の変更',
			'RemoveObject': 'オブジェクトを削除',
			'RemoveScript': 'スクリプトの削除',
			'SetColor': 'カラーを設定',
			'SetGeometry': 'ジオメトリの設定',
			'SetGeometryValue': 'ジオメトリ値の設定',
			'SetMaterialColor': 'マテリアル カラーの設定',
			'SetMaterial': 'マテリアルの設定',
			'SetMaterialMap': 'マテリアル マップの設定',
			'SetMaterialRange': 'マテリアル範囲の設定',
			'SetMaterialValue': 'マテリアル値の設定',
			'SetMaterialVector': '素材のベクトルを設定します',
			'SetPosition': '位置を設定',
			'SetRotation': '回転を設定',
			'SetScale': 'スケールを設定',
			'SetScene': 'セットシーン',
			'SetScriptValue': 'スクリプト値の設定',
			'SetShadowValue': 'Set Shadow Value',
			'SetUuid': 'UUIDの設定',
			'SetValue': '値の設定',

			'file': 'ファイル',
			'new': '新規プロジェクト',
			'empty': '空',
			'arkanoid': 'ブロック崩し',
			'camera': 'カメラ',
			'particles': 'パーティクル',
			'new/Pong': 'ピンポン',
			'shaders': 'シェーダー',
			'open': '開く',
			'save': '保存',
			'import': 'インポート',
			'export': 'エクスポート',

			'edit': '編集',
			'undo': '元に戻す',
			'redo': 'やり直す',
			'center': '中央揃え',
			'clone': '複製',
			'delete': '削除',

			'add': '追加',
			'group': 'グループ',

			'mesh': 'メッシュ',
			'plane': '平面',
			'box': '直方体',
			'capsule': 'カプセル',
			'circle': '円',
			'cylinder': '円柱',
			'ring': 'リング',
			'sphere': '球',
			'dodecahedron': '十二面体',
			'icosahedron': '二十面体',
			'octahedron': '八面体',
			'tetrahedron': '四面体',
			'torus': 'トーラス',
			'tube': 'チューブ',
			'torusknot': 'ノットトーラス',
			'lathe': '旋盤形',
			'sprite': 'スプライト',

			'light': 'ライト',
			'ambient': 'アンビエント',
			'directional': 'ディレクショナル',
			'hemisphere': 'ヘミスフィア',
			'point': 'ポイント',
			'spot': 'スポット',

			'perspective': '透視投影',
			'orthographic': '平行投影',

			'autosave': '自動保存',

			'view': '表示',
			'fullscreen': 'フルスクリーン',
			'gridHelper': 'グリッドヘルパー',
			'cameraHelpers': 'カメラヘルパー',
			'lightHelpers': 'ライトヘルパー',
			'skeletonHelpers': 'スケルトンヘルパー',

			'help': 'ヘルプ',
			'source_code': 'ソースコード',
			'icons': 'アイコンパック',
			'about': 'Three.js について',
			'manual': 'マニュアル',

			'animations': 'アニメーション',
			'play': '再生',
			'stop': '停止',
			'timescale': 'タイムスケール',

			'scene': 'シーン',
			'background': '背景',
			'environment': '環境',
			'fog': '霧',

			'object': 'オブジェクト',
			'geometry': 'ジオメトリ',
			'material': 'マテリアル',
			'script': 'スクリプト',

			'type': 'タイプ',
			'uuid': 'UUID',
			'name': '名前',
			'position': '位置',
			'rotation': '回転',
			'scale': 'スケール',
			'fov': 'Fov',
			'left': '左',
			'right': '右',
			'top': '上',
			'bottom': '下',
			'near': '範囲の開始',
			'far': '範囲の終了',
			'intensity': '強度',
			'color': '色',
			'groundcolor': '地面の色',
			'distance': '距離',
			'angle': '角度',
			'penumbra': '半影',
			'decay': '減衰',
			'shadow': '影',
			'shadowIntensity': 'Shadow Intensity',
			'shadowBias': '影のバイアス',
			'shadowNormalBias': '影のノーマルバイアス',
			'shadowRadius': '影の半径',
			'cast': 'キャスト',
			'receive': 'レシーブ',
			'visible': '表示',
			'frustumcull': 'フラスタムカリング',
			'renderorder': '描画順序',
			'userdata': 'ユーザーデータ',
			'exportjson': 'JSONをエクスポート',

			'geometry/type': 'タイプ',
			'geometry/new': '新規',
			'geometry/uuid': 'UUID',
			'geometry/name': '名前',
			'geometry/bounds': '境界',
			'geometry/userdata': 'ユーザーデータ',
			'geometry/show_vertex_normals': '頂点法線を表示',
			'geometry/compute_vertex_normals': '頂点法線を計算',
			'geometry/compute_vertex_tangents': '接線を計算',
			'geometry/center': '中央',
			'geometry/export': 'JSONをエクスポート',

			'width': '幅',
			'height': '高さ',
			'depth': '奥行き',
			'widthseg': '幅の分割数',
			'heightseg': '高さの分割数',
			'depthseg': '奥行きの分割数',

			'attributes': '属性',
			'index': 'インデックス',
			'morphAttributes': 'モーフ属性',
			'morphRelative': '相対モーフ',

			'radius': '半径',
			'capseg': 'キャップの分割数',
			'radialseg': '円の分割数',

			'segments': 'セグメント',
			'thetastart': '開始角度',
			'thetalength': '角度の大きさ',

			'radiustop': '上部の半径',
			'radiusbottom': '下部の半径',
			'radialsegments': '円の分割数',
			'heightsegments': '高さの分割数',
			'openended': 'ふた',

			'curveSegments': '分割数',
			'steps': 'ステップ',
			'bevelEnabled': 'ベベルを有効にするか',
			'bevelThickness': 'ベベルの厚さ',
			'bevelSize': 'ベベルのサイズ',
			'bevelOffset': 'ベベルのオフセット',
			'bevelSegments': 'ベベルの分割数',
			'shape': '形状に変換',

			'detail': '詳細',

			'phistart': '開始角度',
			'philength': '角度の大きさ',
			'points': 'ポイント',

			'widthsegments': '幅の分割数',

			'innerRadius': '内半径',
			'outerRadius': '外半径',
			'thetaSegments': '円の分割数',
			'phiSegments': 'リングの分割数',

			'extrude': '押し出し',

			'tubularsegments': '大セグメント数',
			'arc': '弧',

			'p': 'P',
			'q': 'Q',

			'path': 'パス',
			'closed': '閉じる',
			'curvetype': 'カーブタイプ',
			'tension': 'テンション',

			'copy': 'コピー',
			'paste': '貼り付け',
			'slot': 'スロット',
			'program': 'プログラム',
			'info': '情報',
			'vertex': '頂点',
			'fragment': 'フラグメント',
			'depthPacking': '深度パッキング',
			'roughness': '粗さ',
			'metalness': '金属度',
			'reflectivity': '反射率',
			'emissive': '発光',
			'specular': '鏡面',
			'shininess': '光沢',
			'clearcoat': 'クリアコート',
			'clearcoatroughness': 'クリアコートの粗さ',
			'dispersion': 'Dispersion',
			'ior': 'IOR',
			'iridescence': '遊色効果',
			'iridescenceIOR': '遊色効果のIOR',
			'iridescenceThicknessMax': '遊色効果の厚さ',
			'sheen': '光沢',
			'sheenroughness': '光沢の粗さ',
			'sheencolor': '光沢の色',
			'transmission': '透過',
			'attenuationDistance': '減衰距離',
			'attenuationColor': '減衰色',
			'thickness': '厚さ',
			'vertexcolors': '頂点色',
			'matcap': 'マットキャップ',
			'map': 'マップ',
			'alphamap': 'アルファマップ',
			'bumpmap': 'バンプマップ',
			'normalmap': 'ノーマルマップ',
			'clearcoatmap': 'クリアコートマップ',
			'clearcoatnormalmap': 'クリアコートノーマルマップ',
			'clearcoatroughnessmap': 'クリアコート粗さマップ',
			'displacementmap': '変位マップ',
			'roughnessmap': '粗さマップ',
			'metalnessmap': 'メタリックマップ',
			'specularmap': '鏡面マップ',
			'iridescencemap': '遊色効果マップ',
			'iridescencethicknessmap': '遊色効果の厚さマップ',
			'sheencolormap': '光沢色マップ',
			'sheenroughnessmap': '光沢粗さマップ',
			'envmap': '環境マップ',
			'lightmap': 'ライトマップ',
			'aomap': 'AOマップ',
			'emissivemap': '発光マップ',
			'gradientmap': 'グラデーションマップ',
			'transmissionmap': '透過マップ',
			'thicknessmap': '厚さマップ',
			'side': '側面',
			'size': 'サイズ',
			'sizeAttenuation': 'サイズ減衰',
			'flatShading': 'フラットシェーディング',
			'blending': 'ブレンディング',
			'opacity': '不透明度',
			'transparent': '透明',
			'forcesinglepass': 'シングルパスを強制',
			'alphatest': 'アルファテスト',
			'depthtest': '深度テスト',
			'depthwrite': '深度書き込み',
			'wireframe': 'ワイヤーフレーム',
			'remove': '削除',

			'project': 'プロジェクト',
			'antialias': 'アンチエイリアス',
			'shadows': 'シャドウ',
			'toneMapping': 'トーンマッピング',
			'materials': 'マテリアル',
			'Assign': '割り当て',

			'app': 'アプリ',
			'title': 'タイトル',
			'editable': '編集可能',
			'publish': 'アプリファイルとして保存',

			'image': '画像',
			'samples': 'サンプル',
			'video': '動画',

			'shading': 'シェーディング',
			'resolution': '解像度',
			'duration': '長さ',
			'render': 'レンダー',

			'settings': '設定',
			'language': '言語',

			'shortcuts': 'ショートカット',
			'translate': '移動',
			'rotate': '回転',
			'focus': 'フォーカス',

			'history': '履歴',
			'clear': 'クリア',
			'persistent': '永続的',

			'local': 'ローカル',

			'grid': 'グリッド',
			'helpers': 'オーバーレイ表示',

			'objects': 'オブジェクト',
			'vertices': '頂点',
			'triangle': '三角形',
			'triangles': '三角形',
			'sample': 'サンプル',
			'rendertime': 'レンダリング時間',

			'vertexShader': '頂点シェーダー',
			'fragmentShader': 'フラグメントシェーダ',
			'programInfo': 'プログラムのプロパティ'

		},

		'ko': {
			'prompt/open': '저장되지 않은 데이터는 손실됩니다. 진행하시겠습니까?',
			'prompt/file/failedToOpenProject': '프로젝트를 여는 데 실패했습니다!',
			'prompt/export/noMeshSelected': '메시가 선택되지 않았습니다!',
			'prompt/export/noObjectSelected': '객체가 선택되지 않았습니다!',
			'prompt/remove': '삭제하시겠습니까?',
			'prompt/clear': '되돌리기/다시하기 기록이 지워집니다. 진행하시겠습니까?',
			'prompt/preserve': '기록은 세션을 통해 저장됩니다. 이는 텍스처를 조작할 때 성능에 영향을 미칠 수 있습니다.',
			'prompt/forbid': '씬을 재생하는 동안 되돌리기/다시하기는 비활성화됩니다.',
			'prompt/rendering/realistic/unsupportedMaterial': 'REALISTIC 셰이딩: MeshStandardmaterial 및 MeshPhysicalmaterial만 지원됩니다',

			'AddObject': '객체 추가',
			'AddScript': '스크립트 추가',
			'MoveObject': '객체 이동',
			'MultiCmds': '여러 변경',
			'RemoveObject': '객체 삭제',
			'RemoveScript': '스크립트 삭제',
			'SetColor': '색 설정',
			'SetGeometry': '지오메트리 설정',
			'SetGeometryValue': '지오메트리 값 설정',
			'SetMaterialColor': '머티리얼 색 설정',
			'SetMaterial': '머티리얼 설정',
			'SetMaterialMap': '머티리얼 맵 설정',
			'SetMaterialRange': '머티리얼 범위 설정',
			'SetMaterialValue': '머티리얼 값 설정',
			'SetMaterialVector': '머티리얼 벡터 설정',
			'SetPosition': '위치 설정',
			'SetRotation': '회전 설정',
			'SetScale': '스케일 설정',
			'SetScene': '장면 설정',
			'SetScriptValue': '스크립트 값 설정',
			'SetShadowValue': '그림자 값 설정',
			'SetUuid': 'UUID 설정',
			'SetValue': '값 설정',

			'file': '파일',
			'new': '새 프로젝트',
			'empty': '비어 있음',
			'arkanoid': '아카노이드',
			'camera': '카메라',
			'particles': '파티클',
			'new/Pong': '퐁',
			'shaders': '셰이더',
			'open': '열기',
			'save': '저장',
			'import': '가져오기',
			'export': '내보내기',

			'edit': '편집',
			'undo': '되돌리기',
			'redo': '다시하기',
			'center': '중앙으로 옮기기',
			'clone': '복제',
			'delete': '삭제',

			'add': '추가',
			'group': '그룹',

			'mesh': '메시',
			'plane': '평면',
			'box': '직육면체',
			'capsule': '캡슐',
			'circle': '원',
			'cylinder': '원통',
			'ring': '링',
			'sphere': '구',
			'dodecahedron': '십이면체',
			'icosahedron': '이십면체',
			'octahedron': '팔면체',
			'tetrahedron': '사면체',
			'torus': '토러스',
			'tube': '튜브',
			'torusknot': '토러스 매듭',
			'lathe': '선반형',
			'sprite': '스프라이트',

			'light': '조명',
			'ambient': '환경광',
			'directional': '방향광',
			'hemisphere': '반구광',
			'point': '포인트',
			'spot': '스포트',

			'perspective': '투시 투영',
			'orthographic': '정사영',

			'autosave': '자동 저장',

			'view': '보기',
			'fullscreen': '전체 화면',
			'gridHelper': '그리드 도우미',
			'cameraHelpers': '카메라 도우미',
			'lightHelpers': '조명 도우미',
			'skeletonHelpers': '골격 도우미',

			'help': '도움말',
			'source_code': '소스 코드',
			'icons': '아이콘 팩',
			'about': 'Three.js 알아보기',
			'manual': '매뉴얼',

			'animations': '애니메이션',
			'play': '재생',
			'stop': '정지',
			'timescale': '시간 스케일',

			'scene': '장면',
			'background': '배경',
			'environment': '환경',
			'fog': '안개',

			'object': '객체',
			'geometry': '지오메트리',
			'material': '머티리얼',
			'script': '스크립트',

			'type': '타입',
			'uuid': 'UUID',
			'name': '이름',
			'position': '위치',
			'rotation': '회전',
			'scale': '스케일',
			'fov': '화각',
			'left': '왼쪽',
			'right': '오른쪽',
			'top': '위',
			'bottom': '아래',
			'near': '최소 시야',
			'far': '최대 시야',
			'intensity': '강도',
			'color': '색',
			'groundcolor': '지면 색',
			'distance': '거리',
			'angle': '각도',
			'penumbra': '반음영',
			'decay': '감쇠',
			'shadow': '그림자',
			'shadowIntensity': '그림자 강도',
			'shadowBias': '그림자 바이어스',
			'shadowNormalBias': '그림자 노멀 바이어스',
			'shadowRadius': '그림자 반지름',
			'cast': 'cast',
			'receive': 'receive',
			'visible': '보임',
			'frustumcull': '프러스텀 컬링',
			'renderorder': '렌더 순서',
			'userdata': '사용자 데이터',
			'exportjson': 'JSON으로 내보내기',

			'geometry/type': '타입',
			'geometry/new': '새로 만들기',
			'geometry/uuid': 'UUID',
			'geometry/name': '이름',
			'geometry/bounds': '경계',
			'geometry/userdata': '사용자 데이터',
			'geometry/show_vertex_normals': '버텍스 노멀 보기',
			'geometry/compute_vertex_normals': '버텍스 노멀 계산',
			'geometry/compute_vertex_tangents': '접선 계산',
			'geometry/center': '중앙',
			'geometry/export': 'JSON으로 내보내기',

			'width': '너비',
			'height': '높이',
			'depth': '깊이',
			'widthseg': '너비 분할 수',
			'heightseg': '높이 분할 수',
			'depthseg': '깊이 분할 수',

			'attributes': '속성',
			'index': '인덱스',
			'morphAttributes': '모프 속성',
			'morphRelative': '상대적 모프',

			'radius': '반지름',
			'capseg': '캡 분할 수',
			'radialseg': '방사 분할 수',

			'segments': '세그먼트',
			'thetastart': '시작 각도',
			'thetalength': '각도 길이',

			'radiustop': '상단 반지름',
			'radiusbottom': '하단 반지름',
			'radialsegments': '방사 분할 수',
			'heightsegments': '높이 분할 수',
			'openended': '끝 열림',

			'curveSegments': '곡선 분할 수',
			'steps': '단계',
			'bevelEnabled': '베벨 사용',
			'bevelThickness': '베벨 두께',
			'bevelSize': '베벨 크기',
			'bevelOffset': '베벨 오프셋',
			'bevelSegments': '베벨 분할 수',
			'shape': '형상으로 변환',

			'detail': '세부화',

			'phistart': '시작 각도',
			'philength': '각도 길이',
			'points': '포인트',

			'widthsegments': '너비 분할 수',

			'innerRadius': '내부 반지름',
			'outerRadius': '외부 반지름',
			'thetaSegments': '원 분할 수',
			'phiSegments': '링 분할 수',

			'extrude': '압출',

			'tubularsegments': '대 분할 수',
			'arc': '호',

			'p': 'P',
			'q': 'Q',

			'path': '경로',
			'closed': '닫기',
			'curvetype': '곡선 타입',
			'tension': '텐션',

			'copy': '복사',
			'paste': '붙여넣기',
			'slot': '슬롯',
			'program': '프로그램',
			'info': '정보',
			'vertex': '버텍스',
			'fragment': '프래그먼트',
			'depthPacking': '깊이 패킹',
			'roughness': '거칠기',
			'metalness': '금속성',
			'reflectivity': '반사율',
			'emissive': '발광',
			'specular': '스펙큘러',
			'shininess': '광택',
			'clearcoat': '클리어 코트',
			'clearcoatroughness': '클리어 코트 거칠기',
			'dispersion': '분산',
			'ior': '굴절률',
			'iridescence': '훈색',
			'iridescenceIOR': '훈색 굴절률',
			'iridescenceThicknessMax': '훈색 두께',
			'sheen': '광택',
			'sheenroughness': '광택 거칠기',
			'sheencolor': '광택 색상',
			'transmission': '투명도',
			'attenuationDistance': '감쇠 거리',
			'attenuationColor': '감쇠 색상',
			'thickness': '두께',
			'vertexcolors': '버텍스 색상',
			'matcap': '매트 캡',
			'map': '맵',
			'alphamap': '알파맵',
			'bumpmap': '범프맵',
			'normalmap': '노멀맵',
			'clearcoatmap': '클리어 코트 맵',
			'clearcoatnormalmap': '클리어 코트 노멀맵',
			'clearcoatroughnessmap': '클리어 코트 거칠기 맵',
			'displacementmap': '변위 맵',
			'roughnessmap': '거칠기 맵',
			'metalnessmap': '금속성 맵',
			'specularmap': '스펙큘러 맵',
			'iridescencemap': '훈색 맵',
			'iridescencethicknessmap': '훈색 두께 맵',
			'sheencolormap': '광택 색상 맵',
			'sheenroughnessmap': '광택 거칠기 맵',
			'envmap': '환경 맵',
			'lightmap': '조명 맵',
			'aomap': 'AO 맵',
			'emissivemap': '발광 맵',
			'gradientmap': '그라디언트 맵',
			'transmissionmap': '투명 맵',
			'thicknessmap': '두께 맵',
			'side': '측면',
			'size': '크기',
			'sizeAttenuation': '크기 감쇠',
			'flatShading': '플랫 셰이딩',
			'blending': '블렌딩',
			'opacity': '불투명도',
			'transparent': '투명',
			'forcesinglepass': '단일 패스 강제',
			'alphatest': '알파 테스트',
			'depthtest': '깊이 테스트',
			'depthwrite': '깊이 쓰기',
			'wireframe': '와이어프레임',
			'remove': '삭제',

			'project': '프로젝트',
			'antialias': '안티앨리어싱',
			'shadows': '그림자',
			'toneMapping': '톤 매핑',
			'materials': '머티리얼',
			'Assign': '할당',

			'app': '앱',
			'title': '제목',
			'editable': '편집 가능',
			'publish': '앱 파일로 저장',

			'image': '이미지',
			'samples': '샘플',
			'video': '비디오',

			'shading': '셰이딩',
			'resolution': '해상도',
			'duration': '길이',
			'render': '렌더',

			'settings': '설정',
			'language': '언어',

			'shortcuts': '단축키',
			'translate': '이동',
			'rotate': '회전',
			'focus': '포커스',

			'history': '기록',
			'clear': '지우기',
			'persistent': '영구적',

			'local': '로컬',

			'grid': '그리드',
			'helpers': '도우미 보기',

			'objects': '객체',
			'vertices': '버텍스',
			'triangle': '삼각형',
			'triangles': '삼각형',
			'sample': '샘플',
			'rendertime': '렌더링 시간',

			'vertexShader': '버텍스 셰이더',
			'fragmentShader': '프래그먼트 셰이더',
			'programInfo': '프로그램 속성'
		}
	};

  String getKey(String key ) {
    return values[ language ]?[ key ] ?? '???';
  }
}
